### ISSUE TITLE
Components subscription to state using hooks

### ISSUE THREAD

**Issue by alexhoma** [trovit/reffects-store#6]
Today we have one way to subscribe our React components suing the method `subscribe()` and it works good for us now.

This is not an issue to change the way we use `subscribe`, but it can be interesting to study another option to subscribe the React components taking advantage of React hooks (https://reactjs.org/docs/hooks-intro.html) and see if it fits to us.

It can provide a simpler and cleaner API to subscribe our components to the state. Example:

* Current `subscribe` high order component:
```javascript
function Component({ prop }) {
  return <span>{value}</span>
}

export default subscribe(Component, function(state) {
    return { prop: state.prop };
})
```

* With `useSubscribe` hook:
```javascript
export default function Component() {
  const prop = useSubscribe(state => state.prop /* or propSelector(state) */);
  return <span>{prop}</span>
}
```
\* `useSubscribe` name is provisional just for the example

**Resources:** 
* https://react-redux.js.org/next/api/hooks#useselector-examples
* https://github.com/react-spring/zustand

**Comment by mariosanchez** [comment]
Seems like an interesting way to explore.

But we need to be sure because we will be shifting from function composition (high order components) to closures (hooks).

It looks syntactically cleaner for me when using it, but not sure about the complexity it could entail.

At least I will do an spike for this.
